name: qr_image_converter
description: A Flutter app to convert images to QR codes and back

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  mobile_scanner: ^2.0.0
  image_picker: ^0.8.5
  image: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
